### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by rth** [QuantStack/mamba#1]
It would be useful to add some CI to run tests.

If we go with Circle CI, we can adapt e.g. [this .circleci/config.yml file](https://github.com/rth/text-vectorize/blob/master/.circleci/config.yml) after removing everything related to python (and rust nightly) from there. 

I can make a PR once we agree on which CI service to use.

**Comment by xyu** [comment]
Looks like Travis has been added in https://github.com/QuantStack/mamba/commit/b20f2506aaf922c440fde35fb36037969dab719f so this can be closed.

**Comment by wolfv** [comment]
true :)
