### ISSUE TITLE
Incorrect solution found for ROOT+Python 3

### ISSUE THREAD

**Issue by chrisburr** [QuantStack/mamba#10]
When using mamba to create an environment for [`root`](https://github.com/conda-forge/root-feedstock/) on macOS it chooses an old `root` build for Python 3. The latest build is chosen for Python 2 and `conda` always behaves as I expect (eventually... 🐌).

### Example

```bash
mamba create --name test-env python=2.7 root --dry-run
```
Chooses: `root               conda-forge/osx-64::root-6.16.00-py27_blas_openblash6de8b3b_7`

```bash
mamba create --name test-env python=3.7 root --dry-run
```
Chooses: `root               conda-forge/osx-64::root-6.16.00-py37_blas_openblash77af0b3_4`

**Comment by wolfv** [comment]
I just opened a PR #11 which fixes the issues for geopandas. might fix yours, too! 

If you do `pip install -e .` from the git clone that should be enough to get a dev version working :)

**Comment by chrisburr** [comment]
Yup that seems to do the trick, thanks!

**Comment by wolfv** [comment]
let us know if you find other issues!
