### ISSUE TITLE
Add support for `conda install --force`

### ISSUE THREAD

**Issue by isuruf** [QuantStack/mamba#117]
It's a useful feature to have

**Comment by wolfv** [comment]
--force-reinstall?

**Comment by wolfv** [comment]
@isuruf sorry for asking again, but you are referring to force-reinstall, right? I agree that force reinstall would be very useful.

**Comment by isuruf** [comment]
Yes it is. I'm still using the `--force` command which is deprecated, but I should switch to `--force-reinstall`.

**Comment by davidbrochart** [comment]
It seems to work already, although it also reinstalls python if it is currently installed. It doesn't hurt, but we may want to skip that part.

**Comment by wolfv** [comment]
This is more properly supported on master now.
