### ISSUE TITLE
Make sure environment creation (with installation) works

### ISSUE THREAD

**Issue by wolfv** [QuantStack/mamba#12]
@jorisvandenbossche observed the following:

Actually, up to now I only looked at what mamba proposed, but now trying to actually create the environment, I get an error for the example above:

...
Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(568): An error occurred while installing package 'conda-forge::attrs-19.1.0-py_0'.
FileNotFoundError(2, "No such file or directory: '/home/joris/miniconda3/envs/mamba-geo-test/bin/python3.7'")
Attempting to roll back.

Rolling back transaction: done

[Errno 2] No such file or directory: '/home/joris/miniconda3/envs/mamba-geo-test/bin/python3.7': '/home/joris/miniconda3/envs/mamba-geo-test/bin/python3.7'

And the rolling back also didn't fully succeed, as the envs/mamba-geo-test dir still has a conda-meta subdir with the file asn1crypto-0.24.0-py37_1003.json in it.

Doing the same with conda properly creates the environment.

**Comment by wolfv** [comment]
first idea: maybe we need to manually add pip into the dependencies, which is something I saw in the conda source code.

**Comment by jorisvandenbossche** [comment]
Copying my comment from the other issue (https://github.com/QuantStack/mamba/issues/9) here:

I get the same error when explicitly adding pip to the required packages (`mamba create -n mamba-geo-test python geopandas cartopy ipython pip`

I have a `add_pip_as_python_dependency` config set to True, so that is the reason that the conda version also installs pip (and `mamba` does not yet follow that config)

**Comment by wolfv** [comment]
I'll need to look into that, or ask on the conda channel. right now i'm not sure what the differences between conda and mamba are here as I am using basically the same installation functions as conda. 

Installing into the main environment on the other hand seems to work quite fine (I've done it, and others over here have done it, too :) Although I wouldn't advise it if you want to keep the environment.

**Comment by wolfv** [comment]
okay, turns out that there is quite a bit of logic that we need to copy over from conda. I didn't really fix the install script to handle new environments. 

E.g. this line 

https://github.com/conda/conda/blob/master/conda/cli/install.py#L275

is currently hard coded to newenv = False I think. 

Should all be easy to fix :)

**Comment by wolfv** [comment]
turns out that a PrefixSetup expects a topo-sorted list of packages. 

Adding this line makes the installation work for now, but it doesn't account for the packages that are to be removed. 

```
    ordered_link_records = IndexedSet(PrefixGraph(to_link_records).graph)
```

**Comment by wolfv** [comment]
we actually do the correct sorting now, so environments should install just fine.
