### ISSUE TITLE
JSON flag

### ISSUE THREAD

**Issue by wolfv** [QuantStack/mamba#130]
We need to have a proper implementation of the `--json` flag.

The first step is to handle it similarly to the `--quiet` flag and hide e.g. the mamba artwork.

**Comment by davidbrochart** [comment]
I opened a PR here: https://github.com/QuantStack/mamba/pull/131

**Comment by wolfv** [comment]
we have a lot more for this now thanks to @davidbrochart ! :)

**Comment by TMiguelT** [comment]
Out of interest, is JSON output now included? Or this just a placeholder like `--quiet` as suggested?

**Comment by davidbrochart** [comment]
Yes it is included, but in order to get the "mamba version" you need to add the `--mamba-experimental` flag also (this flag is going to be removed soon).
