### ISSUE TITLE
[win64] Error then segfault

### ISSUE THREAD

**Issue by dhirschfeld** [QuantStack/mamba#14]
I'm getting the below error:
```
λ  conda create -n tmp732 python=3.7 numpy pandas --dry-run
<snip>
Getting  https://repo.anaconda.com/pkgs/main/win-64
Getting  https://repo.anaconda.com/pkgs/main/noarch
Getting  https://repo.anaconda.com/pkgs/free/win-64
Getting  https://repo.anaconda.com/pkgs/free/noarch
Getting  https://repo.anaconda.com/pkgs/r/win-64
Getting  https://repo.anaconda.com/pkgs/r/noarch
Getting  https://repo.anaconda.com/pkgs/msys2/win-64
Getting  https://repo.anaconda.com/pkgs/msys2/noarch
Getting  https://conda.anaconda.org/conda-forge/win-64
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Miniconda3\envs\mamba\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Miniconda3\envs\mamba\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Miniconda3\envs\mamba\lib\multiprocessing\pool.py", line 470, in _handle_results
    task = get()
  File "C:\Miniconda3\envs\mamba\lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 4 required positional arguments: 'url', 'status_code', 'reason', and 'elapsed_time'
```
...after which python then segfaults.

I'm on win64 with mamba installed in a py37 env.

**Comment by dhirschfeld** [comment]
Sorry, not much to go on but I figured it might be useful to post the traceback in case anyone else runs into similar.

**Comment by dhirschfeld** [comment]
I wouldn't worry about it too much - I'd rather see effort put into development rather that try to support every every platform/environment at this early stage.

**Comment by wolfv** [comment]
Hi @dhirschfeld 

The weird thing is that this seems to be crashing inside the Python code that uses `multiprocessing` to parallelize downloading of the repodata... I was trying to re-use the same code that conda uses (and the same cache). I'm not sure what's going on but I can make a single-threaded version of this part. Multiprocessing doesn't seem to be the right thing to use as it doesn't seem to be good at error reporting.

Maybe you want to make a PR?

It's in this part of the code: https://github.com/QuantStack/mamba/blob/master/mamba/mamba.py#L75-L76

**Comment by martinRenou** [comment]
I have an equivalent error on linux, if that can help finding the issue: 
```
Getting  https://conda.anaconda.org/conda-forge/linux-64
Getting  https://conda.anaconda.org/conda-forge/noarch
Getting  https://repo.anaconda.com/pkgs/main/linux-64
Getting  https://repo.anaconda.com/pkgs/main/noarch
Getting  https://repo.anaconda.com/pkgs/free/linux-64
Getting  https://repo.anaconda.com/pkgs/free/noarch
Getting  https://repo.anaconda.com/pkgs/r/linux-64
Getting  https://repo.anaconda.com/pkgs/r/noarch
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/martin/miniconda3/envs/ipyleaflet/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/martin/miniconda3/envs/ipyleaflet/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/martin/miniconda3/envs/ipyleaflet/lib/python3.7/multiprocessing/pool.py", line 470, in _handle_results
    task = get()
  File "/home/martin/miniconda3/envs/ipyleaflet/lib/python3.7/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'errno'
```

**Comment by wolfv** [comment]
I believe that something happens (like 404 error) in the downloading thread, and multiprocessing doesn't know how to handle exceptions. I should remove multiprocessing here.

**Comment by wolfv** [comment]
Maybe we can switch to a module like this: https://github.com/julienc91/multidl

**Comment by dhirschfeld** [comment]
I have a lot of SSL issues I have to work-around so it's quite likely that's the cause of the problem for me. I'll try again from a box where SSL isn't being interfered with...
