### ISSUE TITLE
Double printing of message

### ISSUE THREAD

**Issue by dhirschfeld** [QuantStack/mamba#193]
I was trying to update a package but the new version hadn't been synced yet so `mamba` printed a message saying I had the latest version... ***twice***! 😱 
```
Looking for: ['terraform-provider-azurerm']

# All requested packages already installed


# All requested packages already installed.


C:\Users\dhirschfeld>
```

Completely harmless but I thought I'd mention it. I'm not certain, but I think it's caused by printing the message in both C++ and Python:
https://github.com/QuantStack/mamba/blob/74cb0f7b994e0c3d1c48c51bdc0f74e8a6472372/mamba/mamba.py#L183-L188
https://github.com/QuantStack/mamba/blob/a96d1c6808a809817a0763dc6e5bafa31aadec2b/src/transaction.cpp#L425-L429

**Comment by wolfv** [comment]
Yes, will be removed! Thanks for finding all these bugs

**Comment by wolfv** [comment]
fixed in master, release will land today
