### ISSUE TITLE
Detect when running without a full TTY

### ISSUE THREAD

**Issue by xhochy** [QuantStack/mamba#196]
I basically only see a blank screen when run without a full TTY. Easiest way to reproduce is to run it inside a docker build. Using `-q` is removing all output and thus is also not a good option.

**Comment by wolfv** [comment]
ok for now you can set `export CI=1`, but we'll need to expose this better.

**Comment by wolfv** [comment]
On UNIX we can use: https://linux.die.net/man/3/isatty

On windows https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/isatty?view=vs-2019

**Comment by wolfv** [comment]
fix is in master :)
