### ISSUE TITLE
How to disable the progress bar?

### ISSUE THREAD

**Issue by xhochy** [QuantStack/mamba#197]
I suspect the progress bar to be the culprit for #196 Sadly `--help` doesn't show an option for this but maybe there is one. How would that be called?

**Comment by wolfv** [comment]
I answered in the other issue (`export CI=1`) but we'll need to fix that by either detecting if TTY or adding more config options. Thanks for testing!

**Comment by wolfv** [comment]
I am closing this because we're now testing for isatty and that should be good .
