### ISSUE TITLE
Decide on the libsolv wrapper

### ISSUE THREAD

**Issue by rth** [QuantStack/mamba#2]
We need to decide how to call libsolv from Rust. As you mentionned @wolfv , the alternatives are,
 1. https://github.com/bkircher/libsolv-rs
 2. https://github.com/ignatenkobrain/libsolv-rs
 3. Write a new wrapper

So far as far as I understand uou went with 1?

That sounds good. Rather than vendoring that code maybe it could be worth forking that repo and adding it as a dependency in `Cargo.toml`,
```
solv = { git = "https://github.com/<user>/libsolv-rs", branch = "<some-branch>" }
```

That would make the separation between the wrapper and this package more clear, while still alowing to make changes to the libsolv-rs fork.

**Comment by wolfv** [comment]
Since this project has evolved to be an extremely thin wrapper around libsolv, switching to rust is unlikely to yield many benefits... Unfortunately :)
