### ISSUE TITLE
Export command does not output dependencies.

### ISSUE THREAD

**Issue by mkcor** [QuantStack/mamba#220]
I noticed that `$ mamba env export` does not output the dependencies of dependencies. Note that this behaviour is that of `$ conda env export --from-history`.

**Comment by mkcor** [comment]
Oops! Correction after I could finally install a dependency explicitly (here, `numpy`): `$ mamba env export` does not output any dependency at all (there is no `dependencies:` field in the output).

**Comment by dhirschfeld** [comment]
Seems to work for me:
<table>
<tr><th><tt>conda env export</tt></th><th><tt>mamba env export</tt></th></tr>
<tr><td><pre>
name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - brotlipy=0.7.0=py37h4ab8f01_1000
  - bzip2=1.0.8=hfa6e2cd_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - cffi=1.14.0=py37ha419a9e_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - conda=4.8.3=py37hc8dfbb8_1
  - conda-package-handling=1.6.0=py37h702c6c1_2
  - cryptography=2.9.2=py37h26f1ce3_0
  - docker=19.03.5=0
  - idna=2.9=py_1
  - krb5=1.17.1=hdd46e55_0
  - libarchive=3.3.3=h0c0e0cf_1008
  - libcurl=7.69.1=h1dcc11c_0
  - libiconv=1.15=hfa6e2cd_1006
  - libsolv=0.7.13=h7bd577a_2
  - libssh2=1.8.2=h642c060_2
  - libxml2=2.9.10=h5d81f1c_1
  - lz4-c=1.9.2=h62dcd97_1
  - lzo=2.10=hfa6e2cd_1000
  - mamba=0.2.6=py37h9da7104_1
  - menuinst=1.4.16=py37_0
  - openssl=1.1.1g=he774522_0
  - pip=20.1=pyh9f0ad1d_0
  - pycosat=0.6.3=py37h8055547_1004
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py_1
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.6=h60c2a47_5_cpython
  - python_abi=3.7=1_cp37m
  - pywin32=227=py37hfa6e2cd_0
  - requests=2.23.0=pyh8c360ce_2
  - ruamel_yaml=0.15.80=py37h8055547_1001
  - setuptools=46.2.0=py37hc8dfbb8_0
  - six=1.14.0=py_1
  - sqlite=3.30.1=hfa6e2cd_0
  - tk=8.6.10=hfa6e2cd_0
  - tqdm=4.46.0=pyh9f0ad1d_0
  - urllib3=1.25.9=py_0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - wheel=0.34.2=py_1
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_1003
  - xz=5.2.5=h2fa13f4_0
  - yaml=0.2.4=he774522_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.4.4=h9f78265_3
prefix: C:\Miniconda
</pre></td>
<td><pre>
name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - brotlipy=0.7.0=py37h4ab8f01_1000
  - bzip2=1.0.8=hfa6e2cd_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - cffi=1.14.0=py37ha419a9e_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - conda=4.8.3=py37hc8dfbb8_1
  - conda-package-handling=1.6.0=py37h702c6c1_2
  - cryptography=2.9.2=py37h26f1ce3_0
  - docker=19.03.5=0
  - idna=2.9=py_1
  - krb5=1.17.1=hdd46e55_0
  - libarchive=3.3.3=h0c0e0cf_1008
  - libcurl=7.69.1=h1dcc11c_0
  - libiconv=1.15=hfa6e2cd_1006
  - libsolv=0.7.13=h7bd577a_2
  - libssh2=1.8.2=h642c060_2
  - libxml2=2.9.10=h5d81f1c_1
  - lz4-c=1.9.2=h62dcd97_1
  - lzo=2.10=hfa6e2cd_1000
  - mamba=0.2.6=py37h9da7104_1
  - menuinst=1.4.16=py37_0
  - openssl=1.1.1g=he774522_0
  - pip=20.1=pyh9f0ad1d_0
  - pycosat=0.6.3=py37h8055547_1004
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py_1
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.6=h60c2a47_5_cpython
  - python_abi=3.7=1_cp37m
  - pywin32=227=py37hfa6e2cd_0
  - requests=2.23.0=pyh8c360ce_2
  - ruamel_yaml=0.15.80=py37h8055547_1001
  - setuptools=46.2.0=py37hc8dfbb8_0
  - six=1.14.0=py_1
  - sqlite=3.30.1=hfa6e2cd_0
  - tk=8.6.10=hfa6e2cd_0
  - tqdm=4.46.0=pyh9f0ad1d_0
  - urllib3=1.25.9=py_0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - wheel=0.34.2=py_1
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_1003
  - xz=5.2.5=h2fa13f4_0
  - yaml=0.2.4=he774522_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.4.4=h9f78265_3
prefix: C:\Miniconda
</pre></td></tr>
</table>

**Comment by dhirschfeld** [comment]
Are you in an activated env?

**Comment by mkcor** [comment]
> Are you in an activated env?

Yes, I created a conda environment named `mamba-gui`, activated it, and installed `mamba` in it (with conda). Oh, I just noticed something odd! From `$ conda env export`, I'm getting:

```
prefix: /home/marianne/miniconda3/envs/mamba-gui
```
But from `$ mamba env export` I'm getting:
```
prefix: /home/marianne/miniconda3/envs/mamba-gui/envs/mamba-gui
```
Uh oh.

**Comment by dhirschfeld** [comment]
![image](https://user-images.githubusercontent.com/881019/81676259-00a2e400-9493-11ea-87c4-fda688bad257.png)


...but that you probably really shouldn't!

**Comment by dhirschfeld** [comment]
I have seen a colleague get into trouble doing this with `conda` so I'm not sure that we can implicate `mamba` for anything yet...

**Comment by mkcor** [comment]
> ...but that you probably really shouldn't!

I would never do that! I swear I haven't:
```
$ ls /home/marianne/miniconda3/envs/mamba-gui/envs/mamba-gui
ls: cannot access '/home/marianne/miniconda3/envs/mamba-gui/envs/mamba-gui': No such file or directory
```

**Comment by dhirschfeld** [comment]
Do mamba & conda agree on the active environment `{conda|mamba} env list`?

Otherwise maybe try from a clean env and see if it's reproducible.

**Comment by mkcor** [comment]
> Do mamba & conda agree on the active environment `{conda|mamba} env list`?

Yes, when run in `(base)`, but not exactly when run in an activated conda env (I mean, not only `mamba-gui` which, of course, might be a little broken by now). More precisely, the same envs are listed but `mamba` looks a bit buggy here:
```
$ mamba env list
# conda environments:
#
                         /home/marianne/miniconda3
                         /home/marianne/miniconda3/envs/announce-voila-reveal
                         /home/marianne/miniconda3/envs/bioinformatica
                         /home/marianne/miniconda3/envs/covid
                         /home/marianne/miniconda3/envs/covid-dashboard
                         /home/marianne/miniconda3/envs/covid-plots
                         /home/marianne/miniconda3/envs/dash-bio-dev
                         /home/marianne/miniconda3/envs/dash-bio-utils
                         /home/marianne/miniconda3/envs/dash-dev
                         /home/marianne/miniconda3/envs/dash_docs
                         /home/marianne/miniconda3/envs/dashbio-demo
                         /home/marianne/miniconda3/envs/dina
                         /home/marianne/miniconda3/envs/fluxgui
                         /home/marianne/miniconda3/envs/gaussian-density
base                  *  /home/marianne/miniconda3/envs/mamba-gui
                         /home/marianne/miniconda3/envs/meteo
                         /home/marianne/miniconda3/envs/nbconvert
                         /home/marianne/miniconda3/envs/py-repr-dina
                         /home/marianne/miniconda3/envs/python-novice-gapminder
                         /home/marianne/miniconda3/envs/scikit-image
                         /home/marianne/miniconda3/envs/skimage-dev
                         /home/marianne/miniconda3/envs/test
                         /home/marianne/miniconda3/envs/voila
                         /home/marianne/miniconda3/envs/voila-dev
                         /home/marianne/miniconda3/envs/voila-hack
                         /home/marianne/miniconda3/envs/voila-reveal
                         /home/marianne/miniconda3/envs/voila-reveal-example
```
instead of
```
$ conda env list
# conda environments:
#
base                     /home/marianne/miniconda3
announce-voila-reveal     /home/marianne/miniconda3/envs/announce-voila-reveal
bioinformatica           /home/marianne/miniconda3/envs/bioinformatica
covid                    /home/marianne/miniconda3/envs/covid
covid-dashboard          /home/marianne/miniconda3/envs/covid-dashboard
covid-plots              /home/marianne/miniconda3/envs/covid-plots
dash-bio-dev             /home/marianne/miniconda3/envs/dash-bio-dev
dash-bio-utils           /home/marianne/miniconda3/envs/dash-bio-utils
dash-dev                 /home/marianne/miniconda3/envs/dash-dev
dash_docs                /home/marianne/miniconda3/envs/dash_docs
dashbio-demo             /home/marianne/miniconda3/envs/dashbio-demo
dina                     /home/marianne/miniconda3/envs/dina
fluxgui                  /home/marianne/miniconda3/envs/fluxgui
gaussian-density         /home/marianne/miniconda3/envs/gaussian-density
mamba-gui             *  /home/marianne/miniconda3/envs/mamba-gui
meteo                    /home/marianne/miniconda3/envs/meteo
nbconvert                /home/marianne/miniconda3/envs/nbconvert
py-repr-dina             /home/marianne/miniconda3/envs/py-repr-dina
python-novice-gapminder     /home/marianne/miniconda3/envs/python-novice-gapminder
scikit-image             /home/marianne/miniconda3/envs/scikit-image
skimage-dev              /home/marianne/miniconda3/envs/skimage-dev
test                     /home/marianne/miniconda3/envs/test
voila                    /home/marianne/miniconda3/envs/voila
voila-dev                /home/marianne/miniconda3/envs/voila-dev
voila-hack               /home/marianne/miniconda3/envs/voila-hack
voila-reveal             /home/marianne/miniconda3/envs/voila-reveal
voila-reveal-example     /home/marianne/miniconda3/envs/voila-reveal-example
```
(not only are the env names missing, but the active env is not named "base").
 
> Otherwise maybe try from a clean env and see if it's reproducible.

Sure thing.

**Comment by wolfv** [comment]
I briefly checked and it seems to work fine for me

For `{conda, mamba} env` we're basically forwarding everything to conda, except for `mamba env create` (or that's how it should be...).

**Comment by mkcor** [comment]
> > Are you in an activated env?
> 
> Yes, I created a conda environment named `mamba-gui`, activated it, and installed `mamba` in it (with conda). Oh, I just noticed something odd! From `$ conda env export`, I'm getting:
> 
> ```
> prefix: /home/marianne/miniconda3/envs/mamba-gui
> ```
> 
> But from `$ mamba env export` I'm getting:
> 
> ```
> prefix: /home/marianne/miniconda3/envs/mamba-gui/envs/mamba-gui
> ```
> 
> Uh oh.

Resolved. I ran into this issue because I didn't know that: *mamba needs to live side-by-side with the real conda*. Closing now!
