### ISSUE TITLE
crash on "inconsistant" envs 

### ISSUE THREAD

**Issue by Carreau** [QuantStack/mamba#23]
While running a conda-install on our cluster I come across an "inconsistent env" (I didn't knew it was  a thing):

```
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/linux-64::mkl-service==1.1.2=py37h90e4bf4_5
  - defaults/linux-64::bottleneck==1.2.1=py37h035aef0_1
  - defaults/linux-64::h5py==2.8.0=py37h989c5e5_3
  - defaults/linux-64::bkcharts==0.2=py37_0
  - defaults/linux-64::pytables==3.4.4=py37ha205bf6_0
  - defaults/linux-64::blaze==0.11.3=py37_0
  - defaults/linux-64::anaconda==5.3.1=py37_0

... then conda normal "trying to solve" and maybe install stuff
```

I thought "Hey, how does mamba handle that ?", so I tried (installing anything does that): 
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "~/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "~/anaconda3/lib/python3.6/site-packages/mamba/mamba.py", line 353, in _wrapped_main
        exit_code = do_call(args, p)
      File "~anaconda3/lib/python3.6/site-packages/mamba/mamba.py", line 332, in do_call
        exit_code = install(args, parser, 'install')
      File "~/anaconda3/lib/python3.6/site-packages/mamba/mamba.py", line 246, in install
        to_link, to_unlink = api.solve(channel_json, installed_json_f.name, mamba_solve_specs, isupdate, strict_priority)
    RuntimeError: Encountered problems while solving.
```
And well it crashed...so just letting you now. 

It's a really small corner case, so feel free to close if you do not really care.

**Comment by wolfv** [comment]
Cool! Thanks for the bug report :) Did mamba print something else?
We probably need to properly extract the error message out of the solver.

Also is there a way for you to extract a yml of the environment?

**Comment by Carreau** [comment]
> Did mamba print something else?

Just something like "an unexpected error has occurred", but nothing useful I believe. 

> Also is there a way for you to extract a yml of the environment?

No , and AFAICT, you can't really as inconsistant seem to happen when another package manager messes with files. I would have exported the env otherwise and provided it to you.

**Comment by wolfv** [comment]
I just switched error handling to not print such aggressive messages anymore. Still need to throw more meaningful errors than runtime error from C++ and properly catch them though!

**Comment by wolfv** [comment]
Closing for now, mamba got quite a bit better at this :)
