### ISSUE TITLE
mamba chooses channels at random (or differently than conda)

### ISSUE THREAD

**Issue by xhochy** [QuantStack/mamba#239]
In the recent days, I see more and more packages being installed from defaults eventhough I have conda-forge as a higher priority channel. I don't have strict channel pinning activated though.

`conda`'s proposed installation:

```
The following NEW packages will be INSTALLED:

  beautifulsoup4     conda-forge/osx-64::beautifulsoup4-4.9.0-py38h32f6830_0
  bzip2              conda-forge/osx-64::bzip2-1.0.8-h0b31af3_2
  conda              conda-forge/osx-64::conda-4.8.3-py38h32f6830_1
  conda-build        conda-forge/osx-64::conda-build-3.18.11-py38_0
  conda-package-han~ conda-forge/osx-64::conda-package-handling-1.6.0-py38h64e0658_2
  filelock           conda-forge/noarch::filelock-3.0.10-py_0
  glob2              conda-forge/noarch::glob2-0.7-py_0
  icu                conda-forge/osx-64::icu-67.1-h4a8c4bd_0
  jinja2             conda-forge/noarch::jinja2-2.11.2-pyh9f0ad1d_0
  libarchive         conda-forge/osx-64::libarchive-3.3.3-h02796b4_1008
  libiconv           conda-forge/osx-64::libiconv-1.15-h0b31af3_1006
  liblief            conda-forge/osx-64::liblief-0.9.0-h3e78482_1
  libxml2            conda-forge/osx-64::libxml2-2.9.10-hc06c4ae_1
  lz4-c              conda-forge/osx-64::lz4-c-1.9.2-h4a8c4bd_1
  lzo                conda-forge/osx-64::lzo-2.10-h1de35cc_1000
  markupsafe         conda-forge/osx-64::markupsafe-1.1.1-py38h64e0658_1
  pkginfo            conda-forge/noarch::pkginfo-1.5.0.1-py_0
  psutil             conda-forge/osx-64::psutil-5.7.0-py38h64e0658_1
  py-lief            conda-forge/osx-64::py-lief-0.9.0-py38h0ceac7d_1
  pycosat            conda-forge/osx-64::pycosat-0.6.3-py38h64e0658_1004
  python-libarchive~ conda-forge/osx-64::python-libarchive-c-2.9-py38_0
  pytz               conda-forge/noarch::pytz-2020.1-pyh9f0ad1d_0
  pyyaml             conda-forge/osx-64::pyyaml-5.3.1-py38h64e0658_0
  ripgrep            conda-forge/osx-64::ripgrep-12.1.0-h0b31af3_0
  ruamel_yaml        conda-forge/osx-64::ruamel_yaml-0.15.80-py38h64e0658_1001
  soupsieve          conda-forge/osx-64::soupsieve-1.9.4-py38h32f6830_1
  yaml               conda-forge/osx-64::yaml-0.2.4-h0b31af3_0
  zstd               conda-forge/osx-64::zstd-1.4.4-h4b3e974_3
```

`mamba` likes to pull a lot of things from defaults:

```
  Package                 Version  Channel                  Size
──────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────

  beautifulsoup4            4.9.0  pkgs/main/osx-64       167 KB
  bzip2                     1.0.8  conda-forge/osx-64     Cached
  conda                     4.8.3  conda-forge/osx-64     Cached
  conda-build             3.18.11  conda-forge/osx-64     515 KB
  conda-package-handling    1.6.1  pkgs/main/osx-64         1 MB
  filelock                 3.0.12  pkgs/main/noarch        13 KB
  glob2                       0.7  conda-forge/noarch      11 KB
  jinja2                   2.11.2  conda-forge/noarch     Cached
  libarchive                3.4.2  pkgs/main/osx-64       711 KB
  libiconv                   1.16  pkgs/main/osx-64       693 KB
  liblief                  0.10.1  pkgs/main/osx-64         2 MB
  libxml2                   2.9.9  pkgs/main/osx-64         1 MB
  lz4-c                     1.9.2  conda-forge/osx-64     Cached
  markupsafe                1.1.1  conda-forge/osx-64     Cached
  pkginfo                 1.5.0.1  pkgs/main/osx-64        43 KB
  psutil                    5.7.0  conda-forge/osx-64     Cached
  py-lief                  0.10.1  pkgs/main/osx-64         1 MB
  pycosat                   0.6.3  conda-forge/osx-64     Cached
  python-libarchive-c         2.9  conda-forge/osx-64      54 KB
  pytz                     2020.1  conda-forge/noarch     Cached
  pyyaml                    5.3.1  conda-forge/osx-64     Cached
  ripgrep                  12.1.0  conda-forge/osx-64     Cached
  ruamel_yaml             0.15.80  conda-forge/osx-64     Cached
  soupsieve                   2.0  pkgs/main/noarch        33 KB
  yaml                      0.2.4  conda-forge/osx-64     Cached
  zstd                      1.4.4  pkgs/main/osx-64       369 KB
```

**Comment by xhochy** [comment]
Present in 0.2.6 and 0.2.7

**Comment by wolfv** [comment]
Thanks again for the bug report! 

I think we should set an increasing sub-priority so that if version numbers are equal, the one with higher sub-priority is chosen (for you that'd be conda-forge).

Should be a simple fix.

**Comment by dhirschfeld** [comment]
As a data point I use `channel_priority=False` so that I can install the latest version of a package from *any* of my specified channels. The channel order is only used to break ties when the versions are equal in more than one channel.

Just mentioning as it would be useful for me to be able to keep that behaviour for `channel_priority=False`

**Comment by wolfv** [comment]
yeah this tie breaking is exactly what the sub-priority is supposed to do. right now we only use sub-priority to discern between noarch and arch-specific packages but we should make another layer of hierarchy there :)

**Comment by xhochy** [comment]
@dhirschfeld Be careful, many packages are not binary-compatible between defaults and conda-forge because of slightly different toolchains. In the past, we had severe issues with conflicting boost packages (now fixed by a run_constraint) but in general, you should avoid mixing both channels. 

In my case, I probably could also remove defaults from my channel list, conda-forge should now be self-sufficent as long as I don't use any CUDA things.

**Comment by dhirschfeld** [comment]
I'm aware of the dangers! They have bitten me, but I protect myself with some judicious (channel) pinning of problematic packages (`pyarrow` and it's deps are some of the pinned packages!)

We have this configuration because internally we have prod/uat/dev channels and we'd like  a `conda update --all` to pull in all the latest prod packages for normal analysts but to pull in all the latest dev builds for developers. Since we also have a conda-forge/defaults mirror (for the parts we use) it works pretty well in practice

**Comment by wolfv** [comment]
@xhochy just to recreate, what were you trying to install here?

**Comment by xhochy** [comment]
`conda-build`

**Comment by wolfv** [comment]
Thanks. I just tested my idea of a fix and it didn't work right out of the box. I will need to investigate this more tomorrow.

**Comment by wolfv** [comment]
I have openend an issue on libsolv https://github.com/openSUSE/libsolv/issues/381, let's wait and see if @mlschroe has some good ideas :) I think it wouldn't be too hard to add this, but using subpriority didn't work the way I thought it would.

**Comment by wolfv** [comment]
I have a fix for libsolv to respect the subpriority above the build numbers. 
However, mamba will still pull more stuff from default than conda, and the reason is that sqlite and py-lief are currently newer on defaults vs conda-forge.
I will make a PR to libsolv and let's see what @mlschroe thinks about it.

**Comment by wolfv** [comment]
Here is the libsolv PR: https://github.com/openSUSE/libsolv/pull/384/files

**Comment by wolfv** [comment]
Should be fixed with the latest libsolv release on conda-forge
