### ISSUE TITLE
Improve output when creating a new environment

### ISSUE THREAD

**Issue by wolfv** [QuantStack/mamba#240]
From @jorisvandenbossche 
When doing an install with conda, there is

```
## Package Plan ##

  environment location: /home/joris/miniconda3/envs/test-conda

  added / updated specs:
    - python=3.8
```

It's not necessarily the most informative output, but at least it gives some indication or clue of "OK, it's installing in 'envs/test-conda', and not installing things in my base env"

**Comment by jorisvandenbossche** [comment]
It's maybe not only for creating an env, but just any time you are installing packages, it might be useful to see a clue/confirmation in which environment it is installing.  
(conda shows the above "Package Plan" in both cases as well)

**Comment by wolfv** [comment]
I have added this in #256 ! Thanks again for the suggestion

**Comment by wolfv** [comment]
Done :)
