### ISSUE TITLE
[Experimental] env creation doesn't list all packages in JSON LINK section

### ISSUE THREAD

**Issue by xhochy** [QuantStack/mamba#245]
`mamba create --mamba-experimental --dry-run --json -n test python=3.8` only lists `python` in LINK, not all other dependencies. They are though all mentioned in FETCH.

This happens in the current master.

**Comment by xhochy** [comment]
Note that without experimental, this looks fine.

**Comment by wolfv** [comment]
yes, thanks. we now have a package cache in C++ and we just need to call `query` on it to figure out if we LINK or FETCH that package.

**Comment by wolfv** [comment]
I think this is fixed with the latest release.
