### ISSUE TITLE
Odd output with PowerShell

### ISSUE THREAD

**Issue by dhirschfeld** [QuantStack/mamba#246]
![image](https://user-images.githubusercontent.com/881019/81937515-105b2d80-9637-11ea-981d-0ddda455f1c5.png)

**Comment by wolfv** [comment]
that's super odd. mamba is using a box drawing character there (something like `─` ...) I was convinced it would work.

Maybe we'll switch back to a regular character like `_` then for the moment.

**Comment by wolfv** [comment]
I fixed this in #253

**Comment by dhirschfeld** [comment]
Thanks - will check it out!
