### ISSUE TITLE
DLL load error

### ISSUE THREAD

**Issue by dhirschfeld** [QuantStack/mamba#249]
With the latest `mamba=0.2.7` I'm seeing DLL load errors:
```
(dev) C:\>mamba install diagrams
Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\mamba-script.py", line 6, in <module>
    from mamba.mamba import main
  File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 52, in <module>
    import mamba.mamba_api as api
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

I saw this with `0.2.6` but I'm not sure if it's specifically related to updating `mamba` or I also did a `conda update --all` in my base (mamba) env around the same time.

**Comment by dhirschfeld** [comment]
I'm literally 15mins into a conda solve so I have plenty of time to report this problem which I've been meaning to do for the last few days 😬

**Comment by dhirschfeld** [comment]
My usual go-to ~~when `conda` struggles~~ is `mamba`, not only because it's so much faster but also because of the useful error messages it gives.

@xhochy's [comment](https://gitter.im/QuantStack/Lobby?at=5ebcfe032baa1918546ac605) gave me a laugh... because I've been there 😭

**Comment by dhirschfeld** [comment]
Ugh, I tried to use `Dependency Walker on `mamba_api.cp37-win_amd64.pyd` and it crashes the program 🙁

**Comment by dhirschfeld** [comment]
I found [Dependencies](https://github.com/lucasg/Dependencies), which is new to me, but at least seemed to work. Unfortunately I can't really decipher it's output;
![image](https://user-images.githubusercontent.com/881019/81943367-a050a580-963e-11ea-84cc-370e44baf9ee.png)

It seems to not like `libcurl.dll`, and IIUC `mamba` bundles it's own version of `libcurl`? So maybe there's a conflict?

Anyway, would be interested if `mamba` works on Windows for anyone else, or if my environment is just uniquely broken!

**Comment by dhirschfeld** [comment]
Tried `dumpbin` but it doesn't seem so useful either:
```
C:\Miniconda3\Lib\site-packages\mamba>dumpbin /dependents .\mamba_api.cp37-win_amd64.pyd
Microsoft (R) COFF/PE Dumper Version 14.21.27619.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file .\mamba_api.cp37-win_amd64.pyd

File Type: DLL

  Image has the following dependencies:

    archive.dll
    solv.dll
    solvext.dll
    libcurl.dll
    libcrypto-1_1-x64.dll
    python37.dll
    MSVCP140.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll

  Summary

        4000 .data
        7000 .pdata
       33000 .rdata
        1000 .reloc
        1000 .rsrc
       91000 .text
```

**Comment by wolfv** [comment]
that sucks! did you see that with 0.2.6 and it resolved or it stayed?

mamba links (dynamically) to libarchive, libcurl, libsolv, libcrypto (openssh) and python, that seems correct...
we might have to make our test coverage on win better.

**Comment by dhirschfeld** [comment]
I'm sure I saw it on 0.2.6 too. Will do some more testing today...

**Comment by wolfv** [comment]
@dhirschfeld I'm not sure I get it completely. Does this happen sporadically or all the time? If it happens all the time, how were you able to produce the other bug reports?! :)

**Comment by dhirschfeld** [comment]
I think it worked once sporadically. No idea how or why as it's otherwise always a DLL error. 

I think most reports were from pre 0.2.6.

Just about to update and do some testing....

**Comment by wolfv** [comment]
impossible! the issue with the unicode characters must have been with a very recent version :)

**Comment by dhirschfeld** [comment]
Yeah - that was the one time I saw it work when I was sure it would give a DLL erro.

Here's a datapoint, update to the latest `mamba=0.2.8`, `conda env export` still gives the DLL error, as does `import mamba.mamba_api as api`
```
(base) C:\> mamba env export
Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\mamba-script.py", line 6, in <module>
    from mamba.mamba import main
  File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 53, in <module>
    import mamba.mamba_api as api
ImportError: DLL load failed: %1 is not a valid Win32 application.

(base) C:\> python
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mamba.mamba_api as api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: %1 is not a valid Win32 application.
>>>
```

**Comment by dhirschfeld** [comment]
I was going to say `mamba list` works... but it doesn't seem to now:
```
(base) C:\> mamba list
Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\mamba-script.py", line 6, in <module>
    from mamba.mamba import main
  File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 53, in <module>
    import mamba.mamba_api as api
ImportError: DLL load failed: %1 is not a valid Win32 application.
```
I was sure it just did before though! 😕

**Comment by dhirschfeld** [comment]
Sorry, none of this is any actionable info :/
I'm going to try on another box...

**Comment by wolfv** [comment]
ok it looks like it's time for me to boot into my windows machine :)
any possibility that there could be a mixup of Python versions?

**Comment by dhirschfeld** [comment]
Well, it seems to work fine on my Win 10 box - just not on my server. So it's likely that something is just stuffed up on my Windows Server 2019 box

**Comment by dhirschfeld** [comment]
...so I'm not sure if there's anything for you to do. Of course if it also works for you that's stronger evidence that it's just my server which is ~~screwed~~ problematic.

**Comment by dhirschfeld** [comment]
I'm on py37 and it looks like `mamba` is py37 also:
```
The following packages will be REMOVED:

  mamba-0.2.8-py37h9da7104_0
```
Just trying a uninstall / reinstall cycle...

**Comment by dhirschfeld** [comment]
The uninstall left an `a.dll` lying around (I'll nuke that)
```
(base) C:\> ls C:\Miniconda3\Lib\site-packages\mamba


    Directory: C:\Miniconda3\Lib\site-packages\mamba


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       15/05/2020  12:17 AM         839680 a.dll
```

**Comment by dhirschfeld** [comment]
No joy - still a DLL error after reinstalling

**Comment by dhirschfeld** [comment]
[WIP] repro

<details>
<summary><b><tt>miniconda.dockerfile</tt></b></summary>

```dockerfile
# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2019

SHELL ["powershell", "-Command", "$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue';"]

RUN $filename = 'Miniconda3-py37_4.8.2-Windows-x86_64.exe'; `
    $url = \"https://repo.anaconda.com/miniconda/$filename\"; `
    $filepath = \"C:/$filename\"; `
    curl.exe -sL $url -o $filepath; `
    $proc = Start-Process $filepath -NoNewWindow -Wait -PassThru -ArgumentList `
        '/S','/InstallationType=AllUsers','/AddToPath=1','/RegisterPython=1','/D=C:\Miniconda';

RUN conda init cmd.exe powershell --system
RUN conda config --prepend channels conda-forge
```
</details>

**Comment by dhirschfeld** [comment]
Since I can't repro on any other box or container other than my server I'll close this as I don't want you to waste your time.

If dozens of other users complain about DLL load errors this can always be reopened.

**Comment by wolfv** [comment]
but we need you to test mamba :(
does your server run on any special windows version? thanks for spending so much time trying to figure this out. I'll try to wrok more on Windows again as well.

**Comment by dhirschfeld** [comment]
Just a normal Windows Server 2019 VM running under VMWare. I did use it for development though so it had accumulated a *lot* of cruft.

Without a repro I don't know that there's much you can do.

I want to test `mamba` too so my next course of action will be to reinstall `miniconda` - start with a clean `base` env. I might not get to that for a bit though as it will be a little disruptive but I'll post back if that was effective.

Hopefully we can write this off as a heisenbug. Not super satisfying but given there's an ~infinite number of ways you can screw up your system it's probably not worth going down this rabbit hole unless it affects >1 person :D

**Comment by dhirschfeld** [comment]
No joy with using the latest version. Still haven't updated my Miniconda base env though.

In case it's useful it does seem to be `libcurl.dll` which is causing the issue:
```python
>>> ctypes.WinDLL(r"C:\Miniconda3\Library\bin\libcurl.dll")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

![image](https://user-images.githubusercontent.com/881019/82291301-16ad2900-99ec-11ea-8b2c-d3d06eb2bc02.png)

**Comment by xhochy** [comment]
@dhirschfeld Can you install `libssh<1.9`?

**Comment by xhochy** [comment]
The 1.9 you probably have installed is broken.

**Comment by xhochy** [comment]
See https://github.com/conda-forge/libssh2-feedstock/pull/37 for a fix.

**Comment by dhirschfeld** [comment]
FANTASTIC! Thanks @xhochy - that "fixed  mamba" for me! 👍

**Comment by rs2** [comment]
@xhochy @dhirschfeld 
```bash
conda install "libssh2<1.9" -n base -c conda-forge
```
results in a significant downgrade of `mamba` itself:
```
The following packages will be DOWNGRADED:

  libssh2                                 1.10.0-h680486a_2 --> 1.8.2-h642c060_2
  mamba                               0.16.0-py36h84e1181_0 --> 0.1.2-py36h090346f_0
```

Do you have a suggestion how to use a relatively recent version of mamba, not `0.1.2`?

**Comment by wolfv** [comment]
What kind of issues are you seeing?

**Comment by rs2** [comment]
> What kind of issues are you seeing?

I'd like to be able to use a relatively recent version of `mamba`. `0.1.2` works.

**Comment by wolfv** [comment]
@rs2 maybe you should open a new issue. this one is really old. 

Many people are using mamba successfully so I am not sure what your problem in particular is. 

You could also give mambaforge a go to start from scratch: https://github.com/conda-forge/miniforge#mambaforge

**Comment by rs2** [comment]
> @rs2 maybe you should open a new issue. this one is really old.
> 
> Many people are using mamba successfully so I am not sure what your problem in particular is.
> 
> You could also give mambaforge a go to start from scratch: https://github.com/conda-forge/miniforge#mambaforge

Sounds good.
