### ISSUE TITLE
Installing with --no-deps throws "Unable to determine python site-packages"

### ISSUE THREAD

**Issue by xhochy** [QuantStack/mamba#282]
Error message:

```
CondaError: Unable to determine python site-packages dir in target_prefix!
Please make sure python is installed in $(pwd)/jl-test2
```

Code to reproduce:

```
mamba create -y -p $(pwd)/jl-test jupyterlab
conda activate $(pwd)/jl-test
conda list --export > env.txt
mamba create -p $(pwd)/jl-test2 --no-deps --file env.txt
```

We probably need to install `python` before any `noarch: python` package.

**Comment by xhochy** [comment]
This worked with `0.2.8` and now fails with `0.2.11`.

**Comment by wolfv** [comment]
wow interesting corner case. 

I need to check what's going on here. The no-deps is throwing out python for some reason, although it's clearly in the specs that are to be added.
