### ISSUE TITLE
Mamba commands have no output (CentOS 6.6)

### ISSUE THREAD

**Issue by eyalbenda** [QuantStack/mamba#293]
I'm trying to use mamba on an old cluster (ha CentOS 6.6 installed). Mamba installs fine through conda, and typing mamba prints out the command options.
However, none of the commands (apart from -V) have any output at all. There is no error, just no output and nothing happens. 
Is there a solution to this?

**Comment by wolfv** [comment]
what shell are you in? do you think I can recreate this in docker?
We don't do anything special. Basically just `std::cout << ...` so I am not entirely sure why this fails.

Also your Python version?

**Comment by wolfv** [comment]
I tested with a docker image and it seemed to work. Do you have any ideas?

**Comment by eyalbenda** [comment]
It seems like a problem with my installation. I'm still unsure why but I managed to install it in a separate conda environment. Closing this, thank you for the support!

**Comment by wolfv** [comment]
Hi @eyalbenda any chance you have a different locale set?

This should fix it: #335
