### ISSUE TITLE
Unable to install caffe-gpu

### ISSUE THREAD

**Issue by ernestp** [QuantStack/mamba#294]
mamba install caffe-gpu

conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/main/linux-64       [====================] (00m:00s) No change
menpo/linux-64           [====================] (00m:00s) No change
menpo/noarch             [====================] (00m:00s) No change

Looking for: ['caffe-gpu']

Encountered problems while solving.
Problem: nothing provides cudatoolkit 8.0.* needed by caffe-gpu-1.0-py27h03f526a_2

**Comment by wolfv** [comment]
did you try with conda?

cudatoolkit 8 is not on defaults anymore according to `mamba repoquery search condatoolkit`

This has nothing to do with mamba :)

**Comment by ernestp** [comment]
Installed cudatookit has version 10.2
Conda uses 10.2, not sure why Mamba wants 8.0

**Comment by wolfv** [comment]
```
{
  "arch": "x86_64",
  "build": "py37hdb72b7a_4",
  "build_number": 4,
  "depends": [
    "blas 1.0 mkl",
    "boost",
    "cudatoolkit 8.0.*",
    "cudnn 7.1.*",
    "gflags >=2.2.1,<2.3.0a0",
    "glog >=0.3.5,<0.3.6.0a0",
    "h5py",
    "hdf5 >=1.8.20,<1.9.0a0",
    "ipython",
    "leveldb >=1.20,<1.21.0a0",
    "libboost >=1.67.0,<1.67.1.0a0",
    "libgcc-ng >=5.4.0",
    "libopencv >=3.4.2,<3.4.3.0a0",
    "libstdcxx-ng >=5.4.0",
    "lmdb >=0.9.22,<1.0a0",
    "matplotlib",
    "mkl >=2018.0.3",
    "networkx",
    "numpy >=1.15.1,<2.0a0",
    "pandas",
    "protobuf",
    "py-boost",
    "py-opencv >=3.4.2,<3.5.0a0",
    "python >=3.7,<3.8.0a0",
    "python-dateutil",
    "python-gflags",
    "python-leveldb",
    "pyyaml",
    "scikit-image",
    "scipy",
    "six",
    "snappy >=1.1.7,<2.0a0"
  ],
  "license": "BSD 2-Clause",
  "license_family": "BSD",
  "name": "caffe-gpu",
  "platform": "linux",
  "requires_features": {
    "blas": "mkl"
  },
  "subdir": "linux-64",
  "timestamp": 1537921967489,
  "version": "1.0"
}
```

**Comment by wolfv** [comment]
you are wrong, conda does _not_ find a solution.

**Comment by ernestp** [comment]
seems issue is in the channel

I have installed caffe-gpu with conda:
```
# Name                    Version          Build             Channel
caffe-gpu                 1.0              py37h999e8d7_5    anaconda
```

**Comment by ernestp** [comment]
mamba install -c anaconda caffe-gpu

pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/main/linux-64       [====================] (00m:00s) No change
anaconda/linux-64        [====================] (00m:00s) No change
anaconda/noarch          [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change

Looking for: ['caffe-gpu']

Encountered problems while solving.
Problem: nothing provides cudatoolkit 8.0.* needed by caffe-gpu-1.0-py27h03f526a_2

**Comment by ernestp** [comment]
Resolved issue by creating new conda env with python 3.7 
(new conda has python 3.8 by default and there is no caffe-gpu for python 3.8)

**Comment by wolfv** [comment]
indeed i was confused by the multiple variants of caffe-gpu: there are packages for cudatoolkit 8, 9, and 10 for python 3.7.

Mamba is not yet very clever in selecting the best cudatoolkit so you might be better off specifying a variant version manually (e.g. `cudatoolkit=10`).

We have an open issue for this #91 

And for the error reporting which could have been improved in this case: #283
