### ISSUE TITLE
`mamba --json repoquery search` doesn't return JSON output

### ISSUE THREAD

**Issue by xhochy** [QuantStack/mamba#295]
It just prints the normal output, no JSON. I'm currently testing this for `mamba --json repoquery --override-channels -c conda-forge search conda-smithy`.

**Comment by davidbrochart** [comment]
What should be the JSON output like? Something like that:
```json
{
    "conda-smithy": [
        {
            "version": "3.7.3",
            "build": "py_0",
            "channel": "conda-forge/noarch"
        },
        {
            "version": "3.7.2",
            "build": "py_0",
            "channel": "conda-forge/noarch"
        }
    ]
}
```

**Comment by xhochy** [comment]
There is already JSON output implemented but not printed: https://github.com/QuantStack/mamba/blob/37748027a947a216d9027a92384a2e595fb1a6da/src/query.cpp#L214-L231

**Comment by davidbrochart** [comment]
I see, then I think the command is `mamba repoquery --json --override-channels -c conda-forge search conda-smithy` (`--json` after `repoquery`, not before).

**Comment by xhochy** [comment]
Yes, this works. Thanks!

**Comment by wolfv** [comment]
indeed. I am too stupid to figure out how to properly add the json flag to sub-sub commands in argparse :) I tried  for a while but gave up for a while :)
