### ISSUE TITLE
No handlers could be found for logger "conda.stderr"

### ISSUE THREAD

**Issue by holmrenser** [QuantStack/mamba#302]
I am trying to create a conda environment on mac with the following command:

```
mamba create -n hisat2 -c bioconda hisat2
```

But get the following error:

```
No handlers could be found for logger "conda.stderr"
```

Seems related to the python logging module?

**Comment by wolfv** [comment]
what is your conda version?

**Comment by holmrenser** [comment]
4.8.3

**Comment by wolfv** [comment]
I briefly tested the command on Linux and it worked for me. Is there any traceback?

**Comment by holmrenser** [comment]
Nope, the above error is all there is. The same command worked on my linux machine as well.

**Comment by wolfv** [comment]
ok I will have to look into this then. I don't have access to a Mac until Monday / Tuesday unfortunately.

**Comment by holmrenser** [comment]
No worries, I'll check back in later next week!

**Comment by holmrenser** [comment]
@wolfv found anything yet?

**Comment by wolfv** [comment]
I just executed your initial command on OS X and it worked fine with the latest version of mamba (0.3.0).

But I'll look further where this could have originated.

**Comment by wolfv** [comment]
I hope this fixes it: https://github.com/QuantStack/mamba/pull/325

Can you still reproduce this error?

**Comment by wolfv** [comment]
I have tried to fix this. Please let me know if you find that this error persists with 0.3.1 (will be released later today).

**Comment by Annazyx** [comment]
I just had this problem and it's fixed now. 
The problem shows after I modified the content of /.condarc, and when I want to reactive conda, it shows 
'
path: ××/.condarc
reason: invalid yaml as line....'
and I delete the content in .condarc.
It works.

**Comment by YeGuoZJU** [comment]
I also get this error, but I did not know how to solve it? 

`No handlers could be found for logger "conda.stderr"`

**Comment by jonashaag** [comment]
Please create a new issue.
