### ISSUE TITLE
package channel specification is ignored when installing

### ISSUE THREAD

**Issue by dremovv** [QuantStack/mamba#310]
Channel specifiction (e.g. `pkgs/main` in `pkgs/main::scipy=1.3.1`) is ignored when `install` command is used:

`scipy v1.3.1` package is available on both `conda-forge` and `pkgs/main` channels. When I install it specifying `pkgs/main` channel, mamba ignores the specification and installs the package from `conda-forge` channel.

- Input:
`mamba install --override-channels -c conda-forge -c pkgs/main pkgs/main::scipy=1.3.1`

- Output:
```
Getting  conda-forge Getting  win-64conda-forge
Getting Getting  noarch
 pkgs/main  pkgs/mainnoarch
win-64

Looking for: ['scipy 1.3.1.*', 'python 3.6.5']

77936 packages in https://conda.anaconda.org/conda-forge/win-64
30335 packages in https://conda.anaconda.org/conda-forge/noarch
29430 packages in https://repo.anaconda.com/pkgs/main/win-64
2831 packages in https://repo.anaconda.com/pkgs/main/noarch

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - pkgs/main::scipy=1.3.1
    - python==3.6.5


The following packages will be SUPERSEDED by a higher-priority channel:

  scipy               pkgs/main::scipy-1.4.1-py36h9439919_0 --> conda-forge::scipy-1.3.1-py36h29ff71c_0
```

These commands work as expected and search package in `pkgs/main` channel:
1. `mamba search --override-channels -c conda-forge -c pkgs/main pkgs/main::scipy=1.3.1`
2. `conda install --override-channels -c conda-forge -c pkgs/main pkgs/main::scipy=1.3.1`

**Comment by wolfv** [comment]
I am happy to report that this should work with the latest version of mamba. What is your version of mamba?

**Comment by wolfv** [comment]
please let me know if it still does not work for you
