### ISSUE TITLE
Implement support for update --all

### ISSUE THREAD

**Issue by dhirschfeld** [QuantStack/mamba#315]
I'm using `mamba` quite a bit these days as the speed is a *huge* win for productivity! :tada:

One situation where I currently have to fallback to `conda` is when I want to update my kitchen-sink environment to to the latest of all packages - `conda update --all`.

Since the environment is very large this can take a long time so it would be great if `mamba` also had this functionality.

**Comment by wolfv** [comment]
Totally agreed. I have some initial work on this, but it's not finished.

**Comment by wolfv** [comment]
implemented a first version of this with #171
