### ISSUE TITLE
Cannot install packages from private channels

### ISSUE THREAD

**Issue by xhochy** [QuantStack/mamba#316]
"private channel" meaning a channel where I have a username:password in my conda configuration. This was working with `0.2.12` and is broken in `0.3.0`. `git bisect`ing leads to 70d214c3059f05c8e58c7027542437c43e986a8a as the offending commit.

**Comment by xhochy** [comment]
The issue here is that the `lookup_dict` doesn't have the credentials in the key where `c` has the credentials.

**Comment by wolfv** [comment]
right, that makes sense, thanks! We'll have to have something better for channels.

**Comment by wolfv** [comment]
fixed in #322
