### ISSUE TITLE
mamba unable to create environment from an explicit file

### ISSUE THREAD

**Issue by brianv0** [QuantStack/mamba#320]
Seems like an easy one to fix, but I just wanted to log it.

index_args is referenced before assignment when using an @EXPLICIT file. 

See line 404 and and 417.

https://github.com/QuantStack/mamba/blob/0.3.0/mamba/mamba.py#L395-L423

**Comment by wolfv** [comment]
do you want to make PR? would be awesome!

**Comment by wolfv** [comment]
I have added a fix in this PR: #322
