### ISSUE TITLE
Throws an "Illegal Instruction: 4" error when looking for packages

### ISSUE THREAD

**Issue by chrisjcameron** [QuantStack/mamba#33]
Platform: macOS 10.13.6 High Sierra
Anaconda Python 3.7

Attempting to execute any update or install command, such as `mamba update mamba -c conda-forge` throws an error right after the `Looking for: ['package']`. 

In `bash` this is `Illegal instruction: 4`  
In `zsh` this is `illegal hardware instruction`

**Comment by wolfv** [comment]
Hi! Thanks for opening this issue.
If your machine does not support AVX2 mamba currently doesn't work (The simdjson dependency has hardcoded instructions).

The good news is that we don't really need simdjson anymore! So with the next release this should be fixed.

**Comment by jpivarski** [comment]
I didn't expect my feedback or search for an answer to be fruitful, but it is: on a Linux environment running within a Chromebook, mamba immediately fails with `Illegal instruction`, no other information. However, I checked `cpuinfo` and indeed, I don't have AVX2 instructions ('cause it's a Chromebook).

(I'm really surprised that SIMD is relevant for interpreting JSON—I didn't think it had regular enough structure.)

I'll just watch this issue to see when an appropriate version is available. Thanks!

**Comment by wolfv** [comment]
Hi Jim, sorry about that. I am working towards removing this dependency – while simdjson is crazy fast, this is not really a big advantage for the JSON sizes we're dealing with (~40Mb).

**Comment by jpivarski** [comment]
Hi, Wolf!

I see this bug as a blessing in disguise because I learned about simdjson and read the paper—now I'm looking for ways to incorporate it into [awkward-array](https://github.com/scikit-hep/awkward-array#awkward-array) as a fast alternative to `awkward.fromiter` (turns JSON-like data into an Arrow-like columnar representation). I can think of applications that _would_ deal with large JSON datasets.

Thanks for (inadvertently) making me aware of this!  :)

**Comment by wolfv** [comment]
Hi @lemire, thanks for pitching in! Runtime dispatching is quite interesting ... I will try to have a look at how you implemented it (we also have a package called `xsimd` (https://github.com/QuantStack/xsimd) which hopefully will have some helper functions for runtime dispatching in the future.

Right now we don't really do a lot of JSON processing internally anymore (it's all moved to `libsolv` itself) which makes mamba a lot leaner.
