### ISSUE TITLE
Download timeouts when creating larger environments

### ISSUE THREAD

**Issue by xhochy** [QuantStack/mamba#332]
Since ~1 week `mamba` randomly aborts the installation of larger environments (~900 packages) with a timeout error. This happens with 0.2.12 and 0.3.4. I'm not sure whether this is a bug or a DDoS protection from cloudflare.

Excerpt from the log: https://gist.github.com/xhochy/2e509f1994341d37fcae83d37c2a538e

**Comment by xhochy** [comment]
All new connection attempts fail with the same log entry:

```
* Connected to conda.anaconda.org (104.17.93.24) port 443 (#53)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /opt/conda/ssl/cacert.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=anaconda.org
*  start date: Feb 28 00:00:00 2020 GMT
*  expire date: Oct  9 12:00:00 2020 GMT
*  subjectAltName: host "conda.anaconda.org" matched cert's "*.anaconda.org"
*  issuer: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=CloudFlare Inc ECC CA-2
*  SSL certificate verify ok.
> GET /conda-forge/linux-64/r-htmltools-0.4.0-r36h0357c0b_1.tar.bz2 HTTP/1.1
Host: conda.anaconda.org
Accept: */*

* Operation timed out after 126 milliseconds with 0 bytes received
* Closing connection 49
```

**Comment by wolfv** [comment]
wow, 900 packages is a lot! 
That's a tough question. Does the retry mechanism work? 
The log says that almost all data has been retrieved for some packages, and then the connection times out:

```
* Operation timed out after 17616 milliseconds with 15518208 out of 16518555 bytes received
* Closing connection 1
* Found bundle for host conda.anaconda.org: 0x55d89124eef0 [serially]
```

I would love to have more insight on what these scenarios look like on the cloudflare side...

We can also try to tune some variables with regards to retrying.

https://github.com/QuantStack/mamba/blob/c4242834b8f002dd1e12996dc45e42222134a36e/include/context.hpp#L60-L64

**Comment by xhochy** [comment]
In 20% of all cases the retry is working. I have like 10s of just retries and then it's working again. Most of the time, it keeps timeouting until all packages until it reaches `max_retries`.

**Comment by wolfv** [comment]
So we are actually setting 

https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html

this option to 60 seconds (which is the read timeout value from conda). 
However, we use this in a curl-multi environment and the manual indicates that this is very wrong.

So I am removing this code, and add a low-speed limit for the moment.
Maybe this will help? I am putting it in a 0.3.6 release (skipping 0.3.5 :)

**Comment by xhochy** [comment]
Note that the timeout also seem to happen with `conda`, it just took me quite some time to check this as `conda` kept on solving for quite some time.

**Comment by wolfv** [comment]
I tested locally and ran into the timeout when creating a new environment with `anaconda` inside. 

I do think that this will help https://github.com/QuantStack/mamba/pull/334 :)

I'll make a release shortly.

**Comment by wolfv** [comment]
0.3.6 is released. I am curious to hear if this helps.

**Comment by xhochy** [comment]
Things passed since then, thanks!

**Comment by wolfv** [comment]
cool!
