### ISSUE TITLE
Make sure sage installs correctly

### ISSUE THREAD

**Issue by wolfv** [QuantStack/mamba#36]
@dimpase @isuruf

Trying to install `sage python=2.7` with `mamba` seems to crash. I am investigating locally. Maybe you can help?
What does the crash say?

**Comment by dimpase** [comment]
it boils down to
```
ImportError: /home/dimpase/miniconda2/envs/sage/lib/python2.7/site-packages/sage/matrix/../../../../liblinboxsage.so.0: undefined symbol: _ZNK6Givaro7IntegercvSsEv
```
- something to do with givaro package, I guess.

**Comment by isuruf** [comment]
It's not a conda issue. It's a packaging issue. Sage hasn't been updated to the new compilers and needs a rebuilt. So, `conda create -n sage sage python=2.7 -c conda-forge/label/cf201901` should work. (`conda-forge/label/cf201901` is a channel with the old packages.)

**Comment by dimpase** [comment]
OK, I tried `mamba create -n sage sage python=2.7 -c conda-forge/label/cf201901` - this gives a working version of Sage 8.3. Great, thanks!

**Comment by wolfv** [comment]
cool! thanks @isuruf for helping out.
