### ISSUE TITLE
Mamba solver is ignored when using `mamba env update`

### ISSUE THREAD

**Issue by tadeu** [QuantStack/mamba#42]
First, I'd like to say that Mamba is an awesome initiative, I've tried `mamba 0.0.7`, and it worked very well with `mamba install` and `mamba create`, sometimes making the solver 15x faster, with no other apparent differences from the results of `conda` commands!

`conda env update` is an important feature, we depend on it to update our environments from `environment.yml` files, especially because of the `--prune` flag, that guarantees that the env is an exact match of the spec defined in `environment.yml` (removing extra packages). I've tried to use `mamba env update`, but it seems to have no effect in the performance this case (looks like it's using `conda` solver).

**Comment by wolfv** [comment]
Hi @tadeu,

indeed, we haven't put in the work to make `mamba env update` work and it's falling back to conda for this command (also the `--prune` flag has not yet been taken care of). It will be a little bit of work ... we need to figure out what arguments to pass to `libsolv` to make it happen :)

**Comment by wolfv** [comment]
I have just made a PR #327 that fixes this. Thanks @jaimergp for insisting :)

**Comment by ahgraber** [comment]
Does #327 enable the `--prune` flag, or is #688 still a valid / outstanding request?
