### ISSUE TITLE
Update install from source instructions?

### ISSUE THREAD

**Issue by mdehollander** [QuantStack/mamba#45]
After merging PR #44 `CMakeLists.txt` is not longer present and running `cmake` throws an error:
```~/src/mamba/include/build$ cmake ..
CMake Error: The source directory "~/src/mamba/include" does not appear to contain CMakeLists.txt.
```

**Comment by wolfv** [comment]
Hi, yep that's true. I need to fix the readme. 

The preferred way of installing is running

```
pip install -e . # for dev installation
pip install . # for non dev installation

# or 

python -m pip install -e . # etc (or use setup.py directly)
```

that's also how the package for conda-forge is built.

**Comment by mdehollander** [comment]
Thanks! After installing  `gcc_linux-64` and `gxx_linux-64` it compiled :)
