### ISSUE TITLE
Make sure that track_features are deprioritized

### ISSUE THREAD

**Issue by wolfv** [QuantStack/mamba#68]
Annoyingly, not everything seems to use mutexes in conda at this point .. 
libclang has two versions: default and hcc where `hcc` adds a track feature that should be ranked lower than default in the default mode.

**Comment by wolfv** [comment]
https://github.com/openSUSE/libsolv/pull/363

**Comment by wolfv** [comment]
this is in the latest build of libsolv on conda-forge.

**Comment by xhochy** [comment]
> Annoyingly, not everything seems to use mutexes in conda at this point ..

Note that this is still actively used in new packages to e.g. downpriotize CUDA support.
