### ISSUE TITLE
Support .conda packages

### ISSUE THREAD

**Issue by wolfv** [QuantStack/mamba#73]
Support is incoming, PR to libsolv _is_ open!

**Comment by wolfv** [comment]
https://github.com/QuantStack/mamba/issues/65#issuecomment-575082462

**Comment by 183amir** [comment]
Hey @wolfv I was trying your fixes here but it seems to work for `mamba search` only. I installed your fork of libsolv and master version of mamba and here is what I get:
```
$ mamba search -c https://idiap.ch/software/bob/conda/label/beta bob.devtools   
Loading channels: done
# Name                       Version           Build  Channel             
bob.devtools                 3.1.2b0  py36h661208a_0  software/bob/conda/label/beta
bob.devtools                 3.1.2b0  py37h661208a_0  software/bob/conda/label/beta
bob.devtools                 3.1.3b0  py36h661208a_0  software/bob/conda/label/beta
bob.devtools                 3.1.3b0  py36h661208a_1  software/bob/conda/label/beta
bob.devtools                 3.1.3b0  py37h661208a_0  software/bob/conda/label/beta
bob.devtools                 3.1.3b0  py37h661208a_1  software/bob/conda/label/beta
bob.devtools                 3.1.4b0  py36h661208a_0  software/bob/conda/label/beta
bob.devtools                 3.1.4b0  py37h661208a_0  software/bob/conda/label/beta


$ mamba create -n temp -c https://idiap.ch/software/bob/conda/label/beta bob.devtools 

Getting  software/bob/conda/label/beta linux-64
https://idiap.ch/software/bob/conda/label/beta/linux-64
Getting  software/bob/conda/label/beta noarch
https://idiap.ch/software/bob/conda/label/beta/noarch
Getting  pkgs/main linux-64
https://repo.anaconda.com/pkgs/main/linux-64
Getting  pkgs/main noarch
https://repo.anaconda.com/pkgs/main/noarch

Looking for: ['bob.devtools']

0 packages in https://idiap.ch/software/bob/conda/label/beta/linux-64
0 packages in https://idiap.ch/software/bob/conda/label/beta/noarch
31925 packages in https://repo.anaconda.com/pkgs/main/linux-64
1411 packages in https://repo.anaconda.com/pkgs/main/noarch
Encountered problems while solving.
Problem: nothing provides requested bob.devtools
```
Looks like the `mamba create` command cannot see the `.conda` packages.

**Comment by wolfv** [comment]
this is how conda removes legacy packages: https://github.com/conda/conda/blob/f4d8ae9f4577008deddf4eb8be52e0abbacf475a/conda/core/subdir_data.py#L402-L432

cc @davidbrochart if you are interested to also take a look at this :)

**Comment by davidbrochart** [comment]
@183amir I tried to reproduce your issue, and now I have another issue:
```
Problem: nothing provides docformatter needed by bob.devtools-3.1.4b0-py36h661208a_1
```
I seems that your channel doesn't provide `docformatter`?

**Comment by 183amir** [comment]
Sorry I forgot to include the non-beta channel:
```
conda create -n temp \
-c https://idiap.ch/software/bob/conda/label/beta \
-c https://idiap.ch/software/bob/conda \
bob.devtools
```

**Comment by davidbrochart** [comment]
> ```
> conda create -n temp \
> -c https://idiap.ch/software/bob/conda/label/beta \
> -c https://idiap.ch/software/bob/conda \
> bob.devtools
> ```

That now works, at least with the latest https://github.com/wolfv/libsolv/tree/add_conda_packages.

**Comment by 183amir** [comment]
The problem is in the `https://idiap.ch/software/bob/conda`  `.tar.bz2`  versions of `bob.devtools` exist. Did you get a beta version of `bob.devtools` installed?

**Comment by davidbrochart** [comment]
Yes:
```
The following NEW packages will be INSTALLED:
  bob.devtools       software/bob/conda/label/beta/linux-64::bob.devtools-3.1.4b0-py37hc0f7268_4
```

**Comment by 183amir** [comment]
I can confirm as well that after updating https://github.com/wolfv/libsolv/tree/add_conda_packages things started working. Thanks a lot.
```
mamba create -n temp \
 --strict-channel-priority \
-c https://idiap.ch/software/bob/conda/label/beta \
-c https://idiap.ch/software/bob/conda \
-c defaults
bob.devtools
```

**Comment by wolfv** [comment]
very cool! We should add the libsolv patch to the build on conda-forge as long as they don't merge it upstream :)

**Comment by davidbrochart** [comment]
@wolfv I'll do that.

**Comment by davidbrochart** [comment]
Done in https://github.com/conda-forge/libsolv-feedstock/pull/20
