### ISSUE TITLE
Feature minimization not respected

### ISSUE THREAD

**Issue by isuruf** [QuantStack/mamba#81]
For eg:

conda create -n pypyp123 python=3.6.9   # gives cpython
mamba create -n pypyp123 python=3.6.9  # gives pypy

**Comment by SylvainCorlay** [comment]
Thanks. this is resolved in https://github.com/openSUSE/libsolv/pull/363 which has not been merged in libsolv yet unfortunately.

**Comment by wolfv** [comment]
fixed in the latest libsolv release on conda-forge :)

**Comment by isuruf** [comment]
This is still an issue with the latest release.

**Comment by wolfv** [comment]
hmm, yeah, this became more complicated because there is a build with build number == 2 for pypy, but not for Python. We'll need to think about how to create a consistent ordering. 

Maybe first order after number of track features, then after build number.

**Comment by wolfv** [comment]
thanks for testing @isuruf !

**Comment by isuruf** [comment]
From what I remember, feature minimization comes before version ordering too.

**Comment by wolfv** [comment]
makes sense

**Comment by wolfv** [comment]
This was fixed in libsolv now.
