### ISSUE TITLE
Python version change

### ISSUE THREAD

**Issue by isuruf** [QuantStack/mamba#82]
I don't have a reproducer where python version was upgraded, but here's an example

conda create -p /home/isuru/miniconda3/envs/py37 python=3.7
conda install opbeat -p /home/isuru/miniconda3/envs/py37   # this errors because opbeat need py<37
mamba install opbeat -p /home/isuru/miniconda3/envs/py37  # Downgrades python to 3.6

**Comment by SylvainCorlay** [comment]
> conda install opbeat -p /home/isuru/miniconda3/envs/py37 # this errors because opbeat need py<37
> mamba install opbeat -p /home/isuru/miniconda3/envs/py37 # Downgrades python to 3.6

Thanks for submitting this. I presume that if the mamba behavior is to be considered incorrect, it means that some packages should special-cased to never be downgraded or upgraded unless explicitly required?

**Comment by isuruf** [comment]
Yes, if mamba is to be a drop-in for conda.

**Comment by SylvainCorlay** [comment]
Is it only python, or also other interpreters or packages?

**Comment by isuruf** [comment]
I've no idea. Sorry.

**Comment by wolfv** [comment]
It's only python as far as i am aware. This should be easy to fix by pinning python to the currently installed version.

**Comment by wolfv** [comment]
this is fixed by pinning python if it's in the environment.

Release is out now (0.1.1) and going to be available on conda-forge soon!

**Comment by isuruf** [comment]
Thanks for fixing this.
