### ISSUE TITLE
Add support for virtual packages

### ISSUE THREAD

**Issue by isuruf** [QuantStack/mamba#84]
Currently conda supports __glibc, __osx, __cuda.

**Comment by wolfv** [comment]
@davidbrochart are you interested in taking a look at this as well?

**Comment by davidbrochart** [comment]
Yes I will.

**Comment by davidbrochart** [comment]
@isuruf I'm looking into supporting virtual packages in mamba, but I'm looking for e.g. a conda package that depends on glibc, that I could make not installable with `export CONDA_OVERRIDE_GLIBC=0.1`. Does such a thing exist?

**Comment by isuruf** [comment]
Thanks @davidbrochart for looking into it. We don't have packages using `__glibc` yet. We do have packages using `__osx` like qt.

**Comment by wolfv** [comment]
I have just checked and indeed the __osx package is used quite a bit in the `constraints` field in the OS X repodata:

https://conda.anaconda.org/conda-forge/osx-64/repodata.json

So we should figure out how to add the virtual packages to the "installed" packages, and make sure that the constraints field works as advertised :)

**Comment by davidbrochart** [comment]
Fixed in #93

**Comment by wolfv** [comment]
:tada:

**Comment by jakirkham** [comment]
I was looking for `__cuda` in the codebase, but didn't find it. Is there somewhere I should be looking?

**Comment by jakirkham** [comment]
NVM I see now ( https://github.com/TheSnakePit/mamba/pull/104 ). So we just use whatever virtual packages Conda has. Is that right?

**Comment by wolfv** [comment]
Yes, that's correct. Let us know if this works well for you guys.

**Comment by jakirkham** [comment]
Thanks Wolf. Will do 🙂
