### ISSUE TITLE
Thinking about a server / client architecture

### ISSUE THREAD

**Issue by wolfv** [QuantStack/mamba#90]
I am thinking about changing some parts of mamba so that the solver could "live on continously" which could enable / speed up some use cases. We could construct the solver once, and then ask for many queries while all the packages etc. stay in memory.

This could enable more interactive explorations of dependencies / solutions e.g. with a web-frontend.

We might be able to dramatically speed up conda-build using this approach (also with some sort of caching mechanism for solutions).

Maybe there are some other potential ideas ... I think @scopatz was also thinking of some tooling to query for packages / solution satisfiability to only trigger the bot once the package is available.

**Comment by scopatz** [comment]
Thanks for looping me in here @wolfv. This really seems like a similar idea to what [conda-metachannel](https://github.com/regro/conda-metachannel/) is or is trying to do (CC @mariusvniekerk).  At least partially.  What I think we really need is a way to perform solves, then return those solves as whole, even if they are a little out of date. The installer should either be able to take a list of package names or the name of the solve they want to use. 

> This could enable more interactive explorations of dependencies / solutions e.g. with a web-frontend.

Yeah. Agreed. But this should probably be different tooling. This is waaay overdue in my opinion.

> We might be able to dramatically speed up conda-build using this approach (also with some sort of caching mechanism for solutions).
> 
> Maybe there are some other potential ideas ... I think @scopatz was also thinking of some tooling to query for packages / solution satisfiability to only trigger the bot once the package is available.

Right, dramaitic speedups should be possible. However, my point w.r.t. the bot is slightly different.  Namely what I think the bot needs as a public API, from Mamba or Conda, that exposes the SAT solver. Don't need to optimize anything, we just need to know if a list of packages is actually satifiable at all so we can make a decision on whether or not to issue a PR or not.  (We don't want to issue a PR where the dependencies aren't installable, and this can happen pretty easily right now). So if Mamba had some easy way of doing this, that would be amazing!  Kinda separate from the client-server questions, unless you are going in there and changing things anyway.

**Comment by scopatz** [comment]
Also, we should really look at [conda-lock](https://github.com/mariusvniekerk/conda-lock) for the solve creation & storage

**Comment by wolfv** [comment]
hey @scopatz 

so mamba just got a lot more "dynamic" where the Python API has changed quite a bit. Now (with the latest PR https://github.com/QuantStack/mamba/pull/102) calling the C++ part looks like:

```py
    pool = api.Pool()
    pool.set_debuglevel(context.verbosity)
    repos = []

    # add installed
    repo = api.Repo(pool, "installed", installed_json_f.name)
    repo.set_installed()
    repos.append(repo)

    for channel_name, cache_file, priority, subpriority in channel_json:
        repo = api.Repo(pool, channel_name, cache_file)
        repo.set_priority(priority, subpriority)
        repos.append(repo)

    solver = api.Solver(pool, solver_options)
    solver.add_jobs(["xtensor >= 1.18"], api.SOLVER_INSTALL)
    success = solver.solve()
    if not success:
        print(solver.problems_to_str())
        return
    
    transaction = api.Transaction(solver)
    to_link, to_unlink = transaction.to_conda()
```

So it would be easy to run multiple jobs over the same in-memory repo-data now (just create a new `api.Solver` instance and add different jobs).
We'll soon expand the API to allow for `queries` (e.g. ask reverse-dependency queries), and we'll integrate `librepo` to parallely and reliably download metadata and packages.

**Comment by scopatz** [comment]
very cool! How long does a full solve take doing it this way?

**Comment by wolfv** [comment]
really depends on the complexity. For xtensor, maybe 0.1 seconds, for something more complex up to two seconds ... 

You'll save the time to load the JSON (or solv cache file) and the setup time for the solver for repeated jobs.

**Comment by scopatz** [comment]
That's fine though.  It isn't going to take minutes per solve. Is this something that has been released in mamba and that I can test out?

**Comment by CJ-Wright** [comment]
@wolfv is there a more complete form of the example usage you gave above? (with all the inputs defined?) I'd be interested in testing this out as well.

**Comment by wolfv** [comment]
@CJ-Wright cool, I am glad you're interested. 

The fullest example is probably the mamba.py on master :) it's a bit of a mess unfortunately right now. I'm working on some more ports to C++ which will also help clean up the Python.

**Comment by wolfv** [comment]
Here is a minimal example of the current API usage. This will probably continue to slightly change but I am going to close this issue for now.

https://gist.github.com/wolfv/cd12bd4a448c77ff02368e97ffdf495a
